### ISSUE TITLE
Should be 2016, rather than 2015?

### ISSUE THREAD

**Issue by trel** [dweinberger/Oscars.JSON#1]
88th academy awards in 2016

**Comment by dweinberger** [comment]
Terrell,

I had it as '16 but changed it to '15 since the Oscars are for movies
released in '15. I'm not sure which is a better way of designating the
results.

David

David W.
david@weinberger.org

**Comment by trel** [comment]
Official site designates them as 2016 Nominees

http://oscar.go.com/news/nominations/oscar-nominations-2016-the-complete-list-of-nominees

**Comment by dweinberger** [comment]
I changed it to 2016 and tried to make it clear in the data.

Thanks!

David W.
david@weinberger.org

**Comment by trel** [comment]
Looks good to me.  06cdfe2
